### ISSUE TITLE
PDF版の図のリンクミス

### ISSUE THREAD

**Issue by ultimatile** [kaityo256/sevendayshpc#19]
PDF版のみですが`6.2 余談：TLB ミスについて`の最初にある図が

```
![スモールページのページウォーク]](fig/smallpage.png)
```

となって表示されていません.

[当該部分のmarkdownは以前修正されている](https://github.com/kaityo256/sevendayshpc/commit/a61c4df57bbe276efbf7ab896edb85c6a9458c7f)ようですが, PDF版は古い版のままのように見えます.
自分でbuildできたらよかったのですが, 手元のmacにpdftkを入れるのが難しそうだったので, お手数ですがPDF版をbuildし直していただけるとありがたいです.

**Comment by kaityo256** [comment]
@ultimatile さん、ご連絡ありがとうございます。
リンクミスを修正した際、ReleaseのPDFは修正したのですが、リポジトリから直接ダウンロードするPDFの修正を忘れておりました。最新版のPDFがダウンロードできるように修正しておきました。
